In [1]:
import numpy as np
List = [1,2,3,4]
print(List)
#array
list = np.array(List)
print("array","-->",list)
#shape and dtype
a  = np.array([[1,2,3],[1,2,3]])
print(a.shape)
print(a.dtype)
b  = np.array([1.0,2.0,3.0])
print(b.dtype)
#zero matrix
x=np.zeros((2,2), dtype=np.int16)
print(x)
#one matrix
y=np.ones((1,2,3), dtype=np.int16)
print(y)
#reshape
a.reshape(3,2)
#flatten
a.flatten()
#horizontal
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))
#vertical
print('Vertical Append:', np.vstack((f, g)))
#randomno
n = np.random.normal(5, 0.5, 10)
print(n)	
#asarray
np.asarray(n)[2]=2
print(n)
#numpyarrange
np.arange(1, 10, 2)
#linspace
np.linspace(1.2, 9.8, num=30)
#logspace
np.logspace(3.0, 4.0, num=4)
#slicing
print('First row:', a[0])
print('Second row:', a[1])
print(a[:2,1])
#min,max,mean,median,std
print(np.min(f))
print(np.max(f)) 
print(np.mean(f))
print(np.median(f))
print(np.std(f))
#numpy dot product
np.dot(f, g)
#matrix multiplication
s= [[1,2],[3,4]] 
d= [[5,6],[7,8]] 
np.matmul(s, d)
#inverse of matrix
print(np.linalg.inv(s))
#determinant
de = np.linalg.det(s)
print(int(de))
#rank  of a matrix
np.linalg.matrix_rank(a)
#eigen value and vector
eigenvalues, eigenvectors = np.linalg.eig([[1,2],[3,4]])
print(eigenvalues, eigenvectors)
#diagonal and transpose
d = np.matrix('[6, 2; 3, 4]')
diag = d.diagonal()
trans = d.transpose()
print(trans)
#trace of a matrix
tracem = d.trace()
print(tracem)


[1, 2, 3, 4]
array --> [1 2 3 4]
(2, 3)
int32
float64
[[0 0]
 [0 0]]
[[[1 1 1]
  [1 1 1]]]
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
[4.88758085 4.81362382 4.78130187 4.67222163 4.91998851 3.92622036
 4.30159949 4.93731938 5.67237063 4.38142378]
[4.88758085 4.81362382 2.         4.67222163 4.91998851 3.92622036
 4.30159949 4.93731938 5.67237063 4.38142378]
First row: [1 2 3]
Second row: [1 2 3]
[2 2]
1
3
2.0
2.0
0.816496580927726
[[-2.   1. ]
 [ 1.5 -0.5]]
-2
[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[6 3]
 [2 4]]
[[10]]
